# Site settings
title: La estadística no muerde
email: angelbravos@posteo.net
description: >- # this means to ignore newlines until "baseurl:"
    Página personal sobre estadística y alguna que otra cosa...
baseurl: "/laestadisticanomuerde" # the subpath of your site, e.g. /blog
url: "http://laestadisticanomuerde.com"
twitter_username: Angel_BravoS
github_username:  AngelBravoS

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
