title: La estadística no muerde
email: angelbravos@posteo.net
description: >-
    Página personal sobre estadística y alguna que otra cosa...
baseurl: "/laestadisticanomuerde" 
url: "localhost:4000"
twitter_username: Angel_BravoS
github_username:  AngelBravoS

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
