# Site settings
title: El blog de Ángel Bravo Sáenz
email: angelbravos@posteo.net
description: >- # this means to ignore newlines until "baseurl:"
    Página personal sobre estadística y alguna que otra cosa...
baseurl: "/JekyllDemo" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Angel_BravoS
github_username:  AngelBravoS

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
